In [1]:
import requests
url = "https://api.coingecko.com/api/v3/coins/markets"

In [2]:
all_data = []

for page in range(1, 7):
    response = requests.get(url, params= {
        "vs_currency": "usd",
        "order": "market_cap_desc",
        "per_page": 100,
        "page": page,
    })
    data = response.json()
    
    if isinstance(data, list):
        all_data.extend(data)

In [3]:
all_data

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 77224,
  'market_cap': 1545460597452,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 1545461832760,
  'total_volume': 59745164297,
  'high_24h': 78240,
  'low_24h': 74419,
  'price_change_24h': 2804.63,
  'price_change_percentage_24h': 3.7687,
  'market_cap_change_24h': 56174647880,
  'market_cap_change_percentage_24h': 3.77192,
  'circulating_supply': 20017171.0,
  'total_supply': 20017187.0,
  'max_supply': 21000000.0,
  'ath': 126080,
  'ath_change_percentage': -38.75027,
  'ath_date': '2025-10-06T18:57:42.558Z',
  'atl': 67.81,
  'atl_change_percentage': 113783.97804,
  'atl_date': '2013-07-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:57.798Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 2423.59,
  'market_cap': 292370944641,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 292370944641,
  'total_volume': 25198443412,
  'high_24h': 2462.81,
  'low_24h': 2319.42,
  'price_change_24h': 95.59,
  'price_change_percentage_24h': 4.10618,
  'market_cap_change_24h': 11546719136,
  'market_cap_change_percentage_24h': 4.11172,
  'circulating_supply': 120690898.2892637,
  'total_supply': 120690898.2892637,
  'max_supply': None,
  'ath': 4946.05,
  'ath_change_percentage': -50.99942,
  'ath_date': '2025-08-24T19:21:03.333Z',
  'atl': 0.432979,
  'atl_change_percentage': 559648.38677,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 40.97647849225858,
   'currency': 'btc',
   'percentage': 4097.6478492258575},
  'last_updated': '2026-04-17T18:33:57.888Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 1.0,
  'market_cap': 185873878309,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 191342727115,
  'total_volume': 99258321265,
  'high_24h': 1.0,
  'low_24h': 1.0,
  'price_change_24h': 0.0001563,
  'price_change_percentage_24h': 0.01563,
  'market_cap_change_24h': 103109586,
  'market_cap_change_percentage_24h': 0.0555,
  'circulating_supply': 185809000661.4175,
  'total_supply': 191275940613.3962,
  'max_supply': None,
  'ath': 1.32,
  'ath_change_percentage': -24.39553,
  'ath_date': '2018-07-24T00:00:00.000Z',
  'atl': 0.572521,
  'atl_change_percentage': 74.72184,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:57.842Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 1.48,
  'market_cap': 91086540096,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 147919390223,
  'total_volume': 4476653832,
  'high_24h': 1.51,
  'low_24h': 1.42,
  'price_change_24h': 0.04363607,
  'price_change_percentage_24h': 3.0422,
  'market_cap_change_24h': 2831448678,
  'market_cap_change_percentage_24h': 3.20826,
  'circulating_supply': 61569680267.0,
  'total_supply': 99985679023.0,
  'max_supply': 100000000000.0,
  'ath': 3.65,
  'ath_change_percentage': -59.4667,
  'ath_date': '2025-07-18T03:40:53.808Z',
  'atl': 0.00268621,
  'atl_change_percentage': 54921.72538,
  'atl_date': '2014-05-22T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:57.495Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 639.94,
  'market_cap': 86224049098,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 86224048554,
  'total_volume': 1515208533,
  'high_24h': 645.76,
  'low_24h': 627.24,
  'price_change_24h': 9.41,
  'price_change_percentage_24h': 1.49161,
  'market_cap_change_24h': 1276947546,
  'market_cap_change_percentage_24h': 1.50323,
  'circulating_supply': 134786764.7,
  'total_supply': 134786763.85,
  'max_supply': 200000000.0,
  'ath': 1369.99,
  'ath_change_percentage': -53.28875,
  'ath_date': '2025-10-13T08:41:24.131Z',
  'atl': 0.0398177,
  'atl_change_percentage': 1607075.15742,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:58.044Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 0.999935,
  'market_cap': 78600440457,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 78627480408,
  'total_volume': 21632845981,
  'high_24h': 1.0,
  'low_24h': 0.998646,
  'price_change_24h': 7.592e-05,
  'price_change_percentage_24h': 0.00759,
  'market_cap_change_24h': -17296858.193756104,
  'market_cap_change_percentage_24h': -0.022,
  'circulating_supply': 78608162629.75993,
  'total_supply': 78635205237.66826,
  'max_supply': None,
  'ath': 1.043,
  'ath_change_percentage': -4.173,
  'ath_date': '2018-11-15T00:00:00.000Z',
  'atl': 0.877647,
  'atl_change_percentage': 13.93206,
  'atl_date': '2023-03-11T08:02:13.981Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:57.855Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 89.08,
  'market_cap': 51300662575,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 55693585070,
  'total_volume': 6756607223,
  'high_24h': 90.46,
  'low_24h': 87.33,
  'price_change_24h': 1.74,
  'price_change_percentage_24h': 1.99338,
  'market_cap_change_24h': 1154092575,
  'market_cap_change_percentage_24h': 2.30144,
  'circulating_supply': 575380938.9220272,
  'total_supply': 624651333.1657138,
  'max_supply': None,
  'ath': 293.31,
  'ath_change_percentage': -69.63126,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 0.500801,
  'atl_change_percentage': 17686.5253,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:57.326Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/photo_2026-04-13_09-59-16.png?1776048311',
  'current_price': 0.326787,
  'market_cap': 30971048029,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 30971047025,
  'total_volume': 577951051,
  'high_24h': 0.327332,
  'low_24h': 0.323496,
  'price_change_24h': 0.00052427,
  'price_change_percentage_24h': 0.16069,
  'market_cap_change_24h': 51448485,
  'market_cap_change_percentage_24h': 0.16639,
  'circulating_supply': 94774635959.9303,
  'total_supply': 94774632886.58519,
  'max_supply': None,
  'ath': 0.431288,
  'ath_change_percentage': -24.22994,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.00180434,
  'atl_change_percentage': 18011.17236,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 170.99338070229047,
   'currency': 'usd',
   'percentage': 17099.33807022905},
  'last_updated': '2026-04-17T18:33:42.592Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 1.037,
  'market_cap': 17337346632,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 17337346632,
  'total_volume': 8519064,
  'high_24h': 1.037,
  'low_24h': 1.023,
  'price_change_24h': 0.0073782,
  'price_change_percentage_24h': 0.71684,
  'market_cap_change_24h': 33029354,
  'market_cap_change_percentage_24h': 0.19087,
  'circulating_supply': 16720458685.507,
  'total_supply': 16720458685.507,
  'max_supply': None,
  'ath': 1.049,
  'ath_change_percentage': -1.16521,
  'ath_date': '2026-03-09T17:00:25.937Z',
  'atl': 0.155357,
  'atl_change_percentage': 567.42848,
  'atl_date': '2025-10-31T14:27:24.456Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:46.553Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 0.100076,
  'market_cap': 15391161200,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 16962808785,
  'total_volume': 2804341803,
  'high_24h': 0.102006,
  'low_24h': 0.096768,
  'price_change_24h': 0.0020051,
  'price_change_percentage_24h': 2.04454,
  'market_cap_change_24h': 288576137,
  'market_cap_change_percentage_24h': 1.91077,
  'circulating_supply': 153870196383.7052,
  'total_supply': 169582443126.5791,
  'max_supply': None,
  'ath': 0.731578,
  'ath_change_percentage': -86.32049,
  'ath_date': '2021-05-08T05:08:23.458Z',
  'atl': 8.69e-05,
  'atl_change_percentage': 115057.60383,
  'atl_date': '2015-05-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:45.310Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 56.16,
  'market_cap': 11984721701,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 17947845985,
  'total_volume': 85838430,
  'high_24h': 56.9,
  'low_24h': 54.33,
  'price_change_24h': 1.83,
  'price_change_percentage_24h': 3.36326,
  'market_cap_change_24h': 392989907,
  'market_cap_change_percentage_24h': 3.39026,
  'circulating_supply': 213418274.0,
  'total_supply': 319606780.0,
  'max_supply': 400000000.0,
  'ath': 64.11,
  'ath_change_percentage': -12.41498,
  'ath_date': '2025-12-10T20:16:13.582Z',
  'atl': 3.06,
  'atl_change_percentage': 1733.8551,
  'atl_date': '2023-02-13T19:01:21.899Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:43.508Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 0.999858,
  'market_cap': 11387590778,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 11387590778,
  'total_volume': 57283909,
  'high_24h': 1.0,
  'low_24h': 0.999509,
  'price_change_24h': -7.3250985982987e-05,
  'price_change_percentage_24h': -0.00733,
  'market_cap_change_24h': 23644242,
  'market_cap_change_percentage_24h': 0.20806,
  'circulating_supply': 11389388526.59124,
  'total_supply': 11389388526.59124,
  'max_supply': None,
  'ath': 1.15,
  'ath_change_percentage': -13.22056,
  'ath_date': '2026-04-02T07:21:14.655Z',
  'atl': 0.948265,
  'atl_change_percentage': 5.43211,
  'atl_date': '2024-10-03T13:19:28.826Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:54.072Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 44.42,
  'market_cap': 10576620256,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 42693934172,
  'total_volume': 345591419,
  'high_24h': 45.46,
  'low_24h': 43.24,
  'price_change_24h': 0.841203,
  'price_change_percentage_24h': 1.93029,
  'market_cap_change_24h': 175188390,
  'market_cap_change_percentage_24h': 1.68427,
  'circulating_supply': 238385315.9541414,
  'total_supply': 962274028.9541414,
  'max_supply': 1000000000.0,
  'ath': 59.3,
  'ath_change_percentage': -25.09685,
  'ath_date': '2025-09-18T03:30:30.650Z',
  'atl': 3.81,
  'atl_change_percentage': 1066.27292,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:45.651Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 0.261451,
  'market_cap': 9662472463,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 11766026793,
  'total_volume': 696268056,
  'high_24h': 0.266982,
  'low_24h': 0.252418,
  'price_change_24h': 0.00656834,
  'price_change_percentage_24h': 2.57701,
  'market_cap_change_24h': 219621531,
  'market_cap_change_percentage_24h': 2.3258,
  'circulating_supply': 36954807980.68808,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 3.09,
  'ath_change_percentage': -91.53035,
  'ath_date': '2021-09-02T06:00:10.474Z',
  'atl': 0.01925275,
  'atl_change_percentage': 1257.99134,
  'atl_date': '2020-03-13T02:22:55.044Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:47.724Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 10.13,
  'market_cap': 9330317849,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 9983044025,
  'total_volume': 495343,
  'high_24h': 10.21,
  'low_24h': 10.04,
  'price_change_24h': -0.057504284980195663,
  'price_change_percentage_24h': -0.56431,
  'market_cap_change_24h': -52797718.4185524,
  'market_cap_change_percentage_24h': -0.56269,
  'circulating_supply': 920821114.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 10.25,
  'ath_change_percentage': -1.14558,
  'ath_date': '2026-04-16T13:15:10.538Z',
  'atl': 0.799859,
  'atl_change_percentage': 1166.75879,
  'atl_date': '2019-12-24T15:14:35.376Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:47.376Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 454.43,
  'market_cap': 9099008515,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 9099008515,
  'total_volume': 270927623,
  'high_24h': 461.12,
  'low_24h': 440.79,
  'price_change_24h': 13.64,
  'price_change_percentage_24h': 3.09471,
  'market_cap_change_24h': 276558381,
  'market_cap_change_percentage_24h': 3.13471,
  'circulating_supply': 20022768.64665078,
  'total_supply': 20022768.64665078,
  'max_supply': 21000000.0,
  'ath': 3785.82,
  'ath_change_percentage': -87.99655,
  'ath_date': '2017-12-20T00:00:00.000Z',
  'atl': 76.93,
  'atl_change_percentage': 490.66761,
  'atl_date': '2018-12-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:47.578Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 9.65,
  'market_cap': 7016654916,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 9650192822,
  'total_volume': 452562417,
  'high_24h': 9.84,
  'low_24h': 9.35,
  'price_change_24h': 0.22413,
  'price_change_percentage_24h': 2.37733,
  'market_cap_change_24h': 156454772,
  'market_cap_change_percentage_24h': 2.28062,
  'circulating_supply': 727099970.4523476,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 52.7,
  'ath_change_percentage': -81.68388,
  'ath_date': '2021-05-10T00:13:57.214Z',
  'atl': 0.148183,
  'atl_change_percentage': 6413.541,
  'atl_date': '2017-11-29T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:47.742Z'},
 {'id': 'memecore',
  'symbol': 'm',
  'name': 'MemeCore',
  'image': 'https://coin-images.coingecko.com/coins/images/53247/large/square-bg-transparent.png?1752637478',
  'current_price': 3.84,
  'market_cap': 6752261882,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 20574387106,
  'total_volume': 17458503,
  'high_24h': 3.87,
  'low_24h': 3.59,
  'price_change_24h': 0.229331,
  'price_change_percentage_24h': 6.35889,
  'market_cap_change_24h': 389141009,
  'market_cap_change_percentage_24h': 6.11557,
  'circulating_supply': 1758632501.18733,
  'total_supply': 5358617081.050776,
  'max_supply': 10000000000.0,
  'ath': 3.87,
  'ath_change_percentage': -0.63474,
  'ath_date': '2026-04-17T13:35:23.985Z',
  'atl': 0.04746135,
  'atl_change_percentage': 7995.12994,
  'atl_date': '2025-07-04T03:56:17.448Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:45.411Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 349.0,
  'market_cap': 6438633681,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 6438633681,
  'total_volume': 126808150,
  'high_24h': 354.13,
  'low_24h': 341.32,
  'price_change_24h': 3.74,
  'price_change_percentage_24h': 1.08388,
  'market_cap_change_24h': 72288858,
  'market_cap_change_percentage_24h': 1.13548,
  'circulating_supply': 18446744.07370955,
  'total_supply': 18446744.07370955,
  'max_supply': None,
  'ath': 797.73,
  'ath_change_percentage': -56.25065,
  'ath_date': '2026-01-14T19:34:07.049Z',
  'atl': 0.216177,
  'atl_change_percentage': 161343.79705,
  'atl_date': '2015-01-14T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:46.854Z'},
 {'id': 'ethena-usde',
  'symbol': 'usde',
  'name': 'Ethena USDe',
  'image': 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059',
  'current_price': 0.999904,
  'market_cap': 5831850223,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 5831850223,
  'total_volume': 78186880,
  'high_24h': 1.0,
  'low_24h': 0.999502,
  'price_change_24h': 8.9e-06,
  'price_change_percentage_24h': 0.00089,
  'market_cap_change_24h': 2117023,
  'market_cap_change_percentage_24h': 0.03631,
  'circulating_supply': 5832209593.011188,
  'total_supply': 5832209593.011188,
  'max_supply': None,
  'ath': 1.034,
  'ath_change_percentage': -3.28364,
  'ath_date': '2025-12-09T17:10:12.652Z',
  'atl': 0.929486,
  'atl_change_percentage': 7.5939,
  'atl_date': '2024-10-04T07:57:15.809Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:54.501Z'},
 {'id': 'canton-network',
  'symbol': 'cc',
  'name': 'Canton',
  'image': 'https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299',
  'current_price': 0.150715,
  'market_cap': 5770780550,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 5770780550,
  'total_volume': 10189794,
  'high_24h': 0.152779,
  'low_24h': 0.146935,
  'price_change_24h': 0.00214202,
  'price_change_percentage_24h': 1.44172,
  'market_cap_change_24h': 81514518,
  'market_cap_change_percentage_24h': 1.43278,
  'circulating_supply': 38326859280.81231,
  'total_supply': 38326859280.81231,
  'max_supply': None,
  'ath': 0.194152,
  'ath_change_percentage': -22.34743,
  'ath_date': '2026-02-03T08:02:08.411Z',
  'atl': 0.059024,
  'atl_change_percentage': 155.42767,
  'atl_date': '2025-12-06T10:32:09.784Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:47.045Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 0.173063,
  'market_cap': 5734805175,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 8648901795,
  'total_volume': 153616918,
  'high_24h': 0.176864,
  'low_24h': 0.164478,
  'price_change_24h': 0.007466,
  'price_change_percentage_24h': 4.50853,
  'market_cap_change_24h': 246057633,
  'market_cap_change_percentage_24h': 4.48295,
  'circulating_supply': 33154556831.69474,
  'total_supply': 50001786868.73495,
  'max_supply': None,
  'ath': 0.875563,
  'ath_change_percentage': -80.25811,
  'ath_date': '2018-01-03T00:00:00.000Z',
  'atl': 0.00047612,
  'atl_change_percentage': 36204.1832,
  'atl_date': '2015-03-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-17T18:33:43.348Z'},
 {'id': 'zcash',
  'symbol': 'zec',
  'name': 'Zcash',
  'image': 'https://coin-images.coingecko.com/coins/images/486/large/circle-zcash-color.png?1696501740',
  'current_price': 332.33,
  'market_cap': 5539285900,
  'market_cap_rank': 23,
  'fully_diluted_valuation': 5539368486,
  'total_volume': 364872955,
  'high_24h': 353.91,
  'low_24h': 330.12,
  'price_change_24h': -4.111049097629291,
  'price_change_percentage_24h': -1.22191,
  'market_cap_change_24h': -69240859.69094372,
  'market_cap_change_percentage_24h': -1.23456,
  'circulating_supply': 16663459.5405448,

In [4]:
import pandas as pd

df = pd.DataFrame(all_data)

In [5]:
df.columns

Index(['id', 'symbol', 'name', 'image', 'current_price', 'market_cap',
       'market_cap_rank', 'fully_diluted_valuation', 'total_volume',
       'high_24h', 'low_24h', 'price_change_24h',
       'price_change_percentage_24h', 'market_cap_change_24h',
       'market_cap_change_percentage_24h', 'circulating_supply',
       'total_supply', 'max_supply', 'ath', 'ath_change_percentage',
       'ath_date', 'atl', 'atl_change_percentage', 'atl_date', 'roi',
       'last_updated'],
      dtype='str')

In [6]:
df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,77224.00,1545460597452,1,1545461832760,5.974516e+10,78240.00,...,2.001719e+07,2.100000e+07,126080.00,-38.75027,2025-10-06T18:57:42.558Z,67.810000,1.137840e+05,2013-07-06T00:00:00.000Z,None,2026-04-17T18:33:57.798Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2423.59,292370944641,2,292370944641,2.519844e+10,2462.81,...,1.206909e+08,NaN,4946.05,-50.99942,2025-08-24T19:21:03.333Z,0.432979,5.596484e+05,2015-10-20T00:00:00.000Z,"{'times': 40.97647849225858, 'currency': 'btc'...",2026-04-17T18:33:57.888Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,1.00,185873878309,3,191342727115,9.925832e+10,1.00,...,1.912759e+11,NaN,1.32,-24.39553,2018-07-24T00:00:00.000Z,0.572521,7.472184e+01,2015-03-02T00:00:00.000Z,None,2026-04-17T18:33:57.842Z
3,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.48,91086540096,4,147919390223,4.476654e+09,1.51,...,9.998568e+10,1.000000e+11,3.65,-59.46670,2025-07-18T03:40:53.808Z,0.002686,5.492173e+04,2014-05-22T00:00:00.000Z,None,2026-04-17T18:33:57.495Z
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,639.94,86224049098,5,86224048554,1.515209e+09,645.76,...,1.347868e+08,2.000000e+08,1369.99,-53.28875,2025-10-13T08:41:24.131Z,0.039818,1.607075e+06,2017-10-19T00:00:00.000Z,None,2026-04-17T18:33:58.044Z

In [7]:
df = df[[
    "id",
    "symbol",
    "name",
    "current_price",
    "market_cap",
    "market_cap_rank",
    "total_volume",
    "price_change_percentage_24h",
    "high_24h",
    "low_24h",
    "circulating_supply",
    "ath",
    "atl",
    "last_updated"
]]

In [8]:
df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,high_24h,low_24h,circulating_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,77224.00,1545460597452,1,5.974516e+10,3.76870,78240.00,74419.00,2.001717e+07,126080.00,67.810000,2026-04-17T18:33:57.798Z
1,ethereum,eth,Ethereum,2423.59,292370944641,2,2.519844e+10,4.10618,2462.81,2319.42,1.206909e+08,4946.05,0.432979,2026-04-17T18:33:57.888Z
2,tether,usdt,Tether,1.00,185873878309,3,9.925832e+10,0.01563,1.00,1.00,1.858090e+11,1.32,0.572521,2026-04-17T18:33:57.842Z
3,ripple,xrp,XRP,1.48,91086540096,4,4.476654e+09,3.04220,1.51,1.42,6.156968e+10,3.65,0.002686,2026-04-17T18:33:57.495Z
4,binancecoin,bnb,BNB,639.94,86224049098,5,1.515209e+09,1.49161,645.76,627.24,1.347868e+08,1369.99,0.039818,2026-04-17T18:33:58.044Z

In [9]:
df["last_updated"] = pd.to_datetime(df["last_updated"])

In [10]:
df = df.dropna()

In [11]:
df.dtypes

id                                             str
symbol                                         str
name                                           str
current_price                              float64
market_cap                                   int64
market_cap_rank                              int64
total_volume                               float64
price_change_percentage_24h                float64
high_24h                                   float64
low_24h                                    float64
circulating_supply                         float64
ath                                        float64
atl                                        float64
last_updated                   datetime64[us, UTC]
dtype: object

In [12]:
df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,high_24h,low_24h,circulating_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,77224.00,1545460597452,1,5.974516e+10,3.76870,78240.00,74419.00,2.001717e+07,126080.00,67.810000,2026-04-17 18:33:57.798000+00:00
1,ethereum,eth,Ethereum,2423.59,292370944641,2,2.519844e+10,4.10618,2462.81,2319.42,1.206909e+08,4946.05,0.432979,2026-04-17 18:33:57.888000+00:00
2,tether,usdt,Tether,1.00,185873878309,3,9.925832e+10,0.01563,1.00,1.00,1.858090e+11,1.32,0.572521,2026-04-17 18:33:57.842000+00:00
3,ripple,xrp,XRP,1.48,91086540096,4,4.476654e+09,3.04220,1.51,1.42,6.156968e+10,3.65,0.002686,2026-04-17 18:33:57.495000+00:00
4,binancecoin,bnb,BNB,639.94,86224049098,5,1.515209e+09,1.49161,645.76,627.24,1.347868e+08,1369.99,0.039818,2026-04-17 18:33:58.044000+00:00

In [13]:
df.shape

(297, 14)

In [ ]:
from datetime import datetime
from pathlib import Path




path = Path(f"../../parquet/data.parquet")
path.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(path)

In [33]:
from pathlib import Path
print(Path(__file__).resolve())

NameError: name '__file__' is not defined

In [1]:
df

NameError: name 'df' is not defined

In [34]:
df.isna().sum()

id                             0
symbol                         0
name                           0
current_price                  0
market_cap                     0
market_cap_rank                0
total_volume                   0
price_change_percentage_24h    0
high_24h                       0
low_24h                        0
circulating_supply             0
ath                            0
atl                            0
last_updated                   0
dtype: int64